groups:
- name: swarm_node.rules
  rules:
  - alert: node_cpu_usage
    expr: 100 - avg (irate(node_cpu_seconds_total{mode="idle"}[1m]))  by (hostname, host_ip) * 100 > 50
    for: 12m
    labels:
      severity: warning
      hostname: '{{ $labels.hostname }}'
      host_ip: '{{ $labels.host_ip }}'
    annotations:
      description: "Swarm node '{{ $labels.hostname }}' which IP is '{{ $labels.host_ip }}'  CPU usage is at '{{ humanize $value}}'%."
      summary: "CPU alert for '{{ $labels.hostname }}' which IP is '{{ $labels.host_ip }}'"
  - alert: node_memory_usage
    expr: sum by (hostname, host_ip) ((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) *100 > 85
    for: 1m
    labels:
      severity: warning
      hostname: '{{ $labels.hostname }}'
      host_ip: '{{ $labels.host_ip }}'
    annotations:
      description: "Swarm node '{{ $labels.hostname }}' which IP is '{{ $labels.host_ip }}' memory usage is at '{{ humanize $value}}'%."
      summary: "Memory alert for '{{ $labels.hostname }}' which IP is '{{ $labels.host_ip }}'"
  - alert: node_disk_usage
    expr: ((node_filesystem_size_bytes{device=~"^/dev/.*$"} - node_filesystem_free_bytes{device=~"^/dev/.*$"}) * 100 / node_filesystem_size_bytes{device=~"^/dev/.*$"}) > 85
    for: 1m
    labels:
      severity: warning
      hostname: '{{ $labels.hostname }}'
      host_ip: '{{ $labels.host_ip }}'
    annotations:
      description: "Swarm node '{{ $labels.hostname }}' which IP is '{{ $labels.host_ip }}' disk usage is at '{{ humanize $value}}'%."
      summary: "Disk alert for '{{ $labels.hostname }}' which IP is '{{ $labels.host_ip }}'"
  - alert: node_disk_fill_rate_6h
    expr: predict_linear(node_filesystem_free_bytes{device=~"^/dev/.*$"}[1h], 6 * 3600) < 0
    for: 1h
    labels:
      severity: critical
      hostname: '{{ $labels.hostname }}'
      host_ip: '{{ $labels.host_ip }}'
    annotations:
      description: "Swarm node '{{ $labels.hostname }}' which IP is '{{ $labels.host_ip }}' disk is going to fill up in 6h."
      summary: "Disk fill alert for '{{ $labels.hostname }}' which IP is '{{ $labels.host_ip }}'"
