global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'promswarm'

rule_files:
  - "swarm_node.rules.yml"
  - "swarm_task.rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    file_sd_configs:
      - files:
          - /etc/prometheus/prometheus/*.json

  - job_name: "cadvisor_exporter"
    file_sd_configs:
      - files:
          - /etc/prometheus/cadvisor_exporter/*.json

  - job_name: 'node_exporter'
    file_sd_configs:
      - files:
          - /etc/prometheus/node_exporter/*.json

  - job_name: 'dockerd_exporter'
    file_sd_configs:
      - files:
          - /etc/prometheus/dockerd_exporter/*.json

  - job_name: 'redis_exporter'
    file_sd_configs:
      - files:
          - /etc/prometheus/redis_exporter/*.json

  - job_name: 'mysqld_exporter'
    file_sd_configs:
      - files:
          - /etc/prometheus/mysqld_exporter/*.json

  - job_name: 'pushgateway'
    file_sd_configs:
      - files:
          - /etc/prometheus/pushgateway/*.json

  # - job_name: 'dockerd-exporter'
  #   dns_sd_configs:
  #   - names:
  #     - 'tasks.dockerd-exporter'
  #     type: 'A'
  #     port: 9323

  # - job_name: 'prometheus'
  #   static_configs:
  #     - targets: ['prometheus:9090']
  #       labels:
  #         instance: prometheus
  #         nodename: {$NODE_NAME}

 