groups:
- name: swarm_task.rules.yml
  rules:
  - alert: task_high_cpu_usage_50
    expr: sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_node_id="", image!=""}[1m])) by (hostname, host_ip, name) * 100 > 50
    for: 2m
    labels:
      severity: warning
      hostname: '{{ $labels.hostname }}'
      host_ip: '{{ $labels.host_ip }}'
    annotations:
      description: "'{{ $labels.name }}' on '{{$labels.hostname }}' which IP is '{{ $labels.host_ip }}' CPU usage is at '{{ humanize $value}}'%."
      summary: "CPU alert for '{{ $labels.name }}' on '{{ $labels.hostname }}' which IP is '{{ $labels.host_ip }}'"
  - alert: task_high_memory_usage_1g
    expr: sum(container_memory_rss{container_label_com_docker_swarm_node_id="", image!=""}) by (hostname, host_ip, name) > 1.2e+09
    for: 1m
    labels:
      severity: warning
      hostname: '{{ $labels.hostname }}'
      host_ip: '{{ $labels.host_ip }}'
    annotations:
      description: "'{{ $labels.name }}' on '{{ $labels.hostname }}' which IP is '{{ $labels.host_ip }}' memory usage is '{{ humanize $value}}'."
      summary: "Memory alert for '{{ $labels.name }}' on '{{ $labels.hostname }}' which IP is '{{ $labels.host_ip }}'"
