
global:
  resolve_timeout: 5m
  # smtp_smarthost: 'localhost:25'
  # smtp_smarthost: 'smtp.gmail.com:587'
  # smtp_smarthost: 'smtp.163.com:25'
  # smtp_smarthost:'smtp.exmail.qq.com:465'
  smtp_smarthost: 'mail.fmsh.com.cn:25'
  smtp_from: 'xxxxxxxxx@fmsh.com.cn'
  smtp_auth_username: 'xxxxxxxx'
  smtp_auth_password: 'xxxxxxxx'
  smtp_require_tls: false

route:
  group_wait: 30s
  group_interval: 5m
  repeat_interval: '8h'
  receiver: 'wechat_platform_system' # 报警接收者
  group_by: [alertname, instance]
  routes:
  - match:
      source: kibana_system
    receiver: wechat_platform_system
    repeat_interval: 99999h
  - match:
      source: kibana_business
    receiver: wechat_kibana_business
    repeat_interval: 99999h
    continue: true
  - match:
      kibana_telephone: true
    receiver: webhook_kibana
    repeat_interval: 99999h
  - match:
      severity: critical
    receiver: wechat_platform_system
    continue: true
  - match:
      severity: critical
    receiver: phone_platform_system
    continue: true
  - match:
      severity: critical
    receiver: e-mail
  - match:
      severity: warning
    receiver: wechat_platform_system
    continue: true
  - match:
      severity: warning
    receiver: e-mail
  - match:
      severity: normal
    receiver: e-mail

templates:
  - '/etc/alertmanager/template/*.tmpl'

receivers:
  - name: 'wechat_platform_system'
    wechat_configs:
    - send_resolved: false
      corp_id: 'wwed369f83bac8cc64'
      to_party: '2'
      agent_id: '1000002'
      api_secret: 'xxxxx-Uxw7OzHml1xJlEt8OHnGulS_bvpCgmz-bfXOI'
      message: '{{ template "platform.system.message" . }}'
         
  - name: 'wechat_kibana_business'
    wechat_configs:
    - send_resolved: false
      corp_id: 'wwed369f83bac8cc64'
      to_party: '2'
      agent_id: '1000002'
      api_secret: 'hAKoT-Uxw7OzHml1xJlEt8OHnGulS_bvpCgmz-bfXOI'
      message: '{{ template "kibana.business.message" . }}'
      
  - name: 'e-mail'
    email_configs:
    - send_resolved: false
      to: 'nfcos_som@fmsh.com.cn,nfcosoms@fmsh.com.cn'
      html: '{{ template "email.default.html" . }}'
      headers: { Subject: " {{ .CommonAnnotations.summary }} " }

  - name: 'slack'
    slack_configs:
      - send_resolved: false
        text: "{{ .CommonAnnotations.description }}"
        username: 'alertmanager'
        channel: 'general'
        api_url: 'https://hooks.slack.com/services/xxxxxxxxxx/BDQMHTQ85/GpyF83O8cbwayObsIGF2LjR6'
        
  - name: 'webhook_kibana'
    webhook_configs:
    - send_resolved: false
      url: 'http://192.168.1.1:19393/api/alert/kibana'

  - name: 'phone_platform_system'
    webhook_configs:
    - send_resolved: false
      url: 'http://192.168.1.1:19393/api/alert/prometheus'
